name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.json') }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
      - name: Check code style
        run: composer cs:check
      - name: Run build
        run: php build.php
