name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy-parcel-pro:
    name: Deploy Parcel Pro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: woo-parcel-pro
          ASSETS_DIR: .wordpress-parcel-pro
  deploy-shops-united:
    name: Deploy Shops United
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: woo-shops-united # TODO: Check this
          ASSETS_DIR: .wordpress-shops-united
