name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - "setup-actions"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: true # TODO: Remove when verified everything works.
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: woo-parcel-pro
