name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # The WooCommerce plugin versions to test against.
        # The empty string is necessary to test against the latest version.
        wc-version: ['', 7.9.0]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      wordpress:
        image: wordpress:6
        ports:
          - '80:80'
        volumes:
          - '.:/var/www/html/wp-content/plugins/parcelpro'
        env:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress
        options: --name wordpress
      db:
        image: mariadb:11
        ports:
          - '3306:3306'
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_USER: wordpress
          MARIADB_PASSWORD: wordpress
          MARIADB_DATABASE: wordpress
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
      working-directory: tests
    - run: npx playwright install chromium --with-deps
      working-directory: tests
    - name: Setup
      run: |
        composer build parcelpro
        ./setup.sh ${{ matrix.wc-version }}
        echo "USER_ID=${{ secrets.PP_USER_ID }}" >> tests/.env
        echo "API_KEY=${{ secrets.PP_API_KEY }}" >> tests/.env
    - run: npm test
      working-directory: tests
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: tests/playwright-report/
        retention-days: 30
