name: Update assets on WordPress.org

on:
  push:
    branches:
      - main

jobs:
  assets:
    name: Update assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: php build.php
      - name: Update Parcel Pro assets
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: woo-parcel-pro
          ASSETS_DIR: .wordpress-parcel-pro
          IGNORE_OTHER_FILES: true
      - name: Update Shops United assets
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: woo-shops-united # TODO: Check this
          ASSETS_DIR: .wordpress-shops-united # TODO: Update assets to Shops United branding
          IGNORE_OTHER_FILES: true
